-- Phase 13A — add CHAOS, FOFA, UNCOVER API provider slots.
ALTER TYPE "ApiProvider" ADD VALUE IF NOT EXISTS 'CHAOS';
ALTER TYPE "ApiProvider" ADD VALUE IF NOT EXISTS 'FOFA';
ALTER TYPE "ApiProvider" ADD VALUE IF NOT EXISTS 'UNCOVER';
