import type { Queue } from 'bullmq';
import type { PrismaService } from '@autoscanner/database';
import type { ScanJobPayload } from '@autoscanner/queues';
import type { ScannerRegistry } from '@autoscanner/scanner-sdk';
import type { TemplateStep } from '@autoscanner/templates';

import { ContextBuilder } from '../context-builder.service';
import type { OrchestratorRedisSubscriber } from '../orchestrator-redis.tokens';
import { StepExecutor, StepTimeoutError, StepFailedError } from '../step-executor.service';

type TemplateRun = {
  id: string;
  templateId: string;
  templateName: string;
  engagementId: string;
  target: string;
  status: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'CANCELLED';
  currentStepIndex: number;
  startedAt: Date | null;
  completedAt: Date | null;
  errorMessage: string | null;
  createdById: string;
  createdAt: Date;
  updatedAt: Date;
};

function makeRun(overrides: Partial<TemplateRun> = {}): TemplateRun {
  return {
    id: 'run_1',
    templateId: 'tpl_1',
    templateName: 'recon-passive',
    engagementId: 'eng_1',
    target: 'example.com',
    status: 'RUNNING',
    currentStepIndex: 0,
    startedAt: new Date(),
    completedAt: null,
    errorMessage: null,
    createdById: 'user_1',
    createdAt: new Date(),
    updatedAt: new Date(),
    ...overrides,
  };
}

function makePrisma(): jest.Mocked<PrismaService> {
  const prisma = {
    subdomain: {
      findMany: jest.fn().mockResolvedValue([]),
    },
    ipAddress: {
      findMany: jest.fn().mockResolvedValue([]),
    },
    scan: {
      create: jest
        .fn()
        .mockImplementation(({ data }: { data: Record<string, unknown> }) =>
          Promise.resolve({ id: 'scan_1', ...data }),
        ),
    },
    scanJob: {
      // `id` defaults to a random UUID generated by StepExecutor; tests that
      // care about the id assert against the `data.id` echoed back here, or
      // against the `scanJobId` payload sent to the BullMQ queue.
      create: jest
        .fn()
        .mockImplementation(({ data }: { data: Record<string, unknown> }) =>
          Promise.resolve({ status: 'PENDING', ...data }),
        ),
      findUnique: jest.fn().mockResolvedValue(null),
    },
    // C2: dispatchOne wraps scan+scanJob creation in a single $transaction.
    // The mock just invokes the callback with `prisma` itself as the tx
    // client so `tx.scan.create` / `tx.scanJob.create` route to the same
    // jest.fn() instances asserted by the existing specs.
    $transaction: jest.fn(async (cb: (tx: unknown) => Promise<unknown>) => cb(prisma)),
  } as unknown as jest.Mocked<PrismaService>;
  return prisma;
}

function makeRedis(): jest.Mocked<OrchestratorRedisSubscriber> {
  return {
    subscribe: jest.fn().mockResolvedValue(undefined),
    unsubscribe: jest.fn().mockResolvedValue(undefined),
    on: jest.fn(),
    off: jest.fn(),
    quit: jest.fn().mockResolvedValue(undefined),
  } as unknown as jest.Mocked<OrchestratorRedisSubscriber>;
}

function makeScannerRegistry(timeoutMs = 600_000): ScannerRegistry {
  return {
    get: jest.fn().mockReturnValue({
      name: 'subfinder',
      docker: { defaultTimeoutMs: timeoutMs },
    }),
  } as unknown as ScannerRegistry;
}

function makeScanQueue(): jest.Mocked<Queue<ScanJobPayload>> {
  return {
    add: jest.fn().mockResolvedValue({}),
  } as unknown as jest.Mocked<Queue<ScanJobPayload>>;
}

function build(
  prisma: jest.Mocked<PrismaService>,
  registry: ScannerRegistry,
  queue: jest.Mocked<Queue<ScanJobPayload>>,
  redis: jest.Mocked<OrchestratorRedisSubscriber>,
  pollIntervalMs = 5_000,
): StepExecutor {
  const ctxBuilder = new ContextBuilder(prisma);
  return new StepExecutor(prisma, registry, queue, redis, ctxBuilder, { pollIntervalMs });
}

describe('StepExecutor target resolution (via ContextBuilder)', () => {
  it('kind=context path=target -> [templateRun.target] (root domain)', async () => {
    const prisma = makePrisma();
    const ctx = new ContextBuilder(prisma);
    const run = makeRun({ target: 'acme.com' });
    const step: TemplateStep = {
      scannerName: 'subfinder',
      inputs: {},
      target: { kind: 'context', path: 'target' },
    };

    const targets = await ctx.buildTargets(step, run, 0);

    expect(targets).toEqual(['acme.com']);
    expect(prisma.subdomain.findMany).not.toHaveBeenCalled();
  });

  it('kind=context path=subdomains -> canonicalValues from prisma.subdomain', async () => {
    const prisma = makePrisma();
    (prisma.subdomain.findMany as jest.Mock).mockResolvedValueOnce([
      { canonicalValue: 'api.acme.com' },
      { canonicalValue: 'mail.acme.com' },
    ]);
    const ctx = new ContextBuilder(prisma);
    const step: TemplateStep = {
      scannerName: 'httpx',
      inputs: {},
      target: { kind: 'context', path: 'subdomains' },
    };

    const targets = await ctx.buildTargets(step, makeRun({ engagementId: 'eng_xyz' }), 1);

    expect(prisma.subdomain.findMany).toHaveBeenCalledWith({
      where: { engagementId: 'eng_xyz' },
    });
    expect(targets).toEqual(['api.acme.com', 'mail.acme.com']);
  });

  it('kind=context path=urls -> host strings of Subdomain rows with httpStatus IS NOT NULL', async () => {
    const prisma = makePrisma();
    (prisma.subdomain.findMany as jest.Mock).mockResolvedValueOnce([
      { canonicalValue: 'www.acme.com', httpStatus: 200 },
    ]);
    const ctx = new ContextBuilder(prisma);
    const step: TemplateStep = {
      scannerName: 'somewhere',
      inputs: {},
      target: { kind: 'context', path: 'urls' },
    };

    const targets = await ctx.buildTargets(step, makeRun({ engagementId: 'eng_x' }), 2);

    expect(prisma.subdomain.findMany).toHaveBeenCalledWith({
      where: { engagementId: 'eng_x', httpStatus: { not: null } },
    });
    expect(targets).toEqual(['www.acme.com']);
  });

  it('kind=context path=ipAddresses -> addresses from prisma.ipAddress', async () => {
    const prisma = makePrisma();
    (prisma.ipAddress.findMany as jest.Mock).mockResolvedValueOnce([
      { address: '10.0.0.1' },
      { address: '10.0.0.2' },
    ]);
    const ctx = new ContextBuilder(prisma);
    const step: TemplateStep = {
      scannerName: 'nmap',
      inputs: {},
      target: { kind: 'context', path: 'ipAddresses' },
    };

    const targets = await ctx.buildTargets(step, makeRun({ engagementId: 'eng_q' }), 1);

    expect(prisma.ipAddress.findMany).toHaveBeenCalledWith({
      where: { engagementId: 'eng_q' },
    });
    expect(targets).toEqual(['10.0.0.1', '10.0.0.2']);
  });

  it('D3 fallback: empty resolved list AND stepIndex > 0 -> [templateRun.target]', async () => {
    const prisma = makePrisma();
    (prisma.subdomain.findMany as jest.Mock).mockResolvedValueOnce([]);
    const ctx = new ContextBuilder(prisma);
    const step: TemplateStep = {
      scannerName: 'httpx',
      inputs: {},
      target: { kind: 'context', path: 'subdomains' },
    };

    const targets = await ctx.buildTargets(step, makeRun({ target: 'fallback.example.com' }), 2);

    expect(targets).toEqual(['fallback.example.com']);
  });

  it('D3 NOT applied on step 0: empty list at stepIndex=0 stays empty', async () => {
    const prisma = makePrisma();
    (prisma.subdomain.findMany as jest.Mock).mockResolvedValueOnce([]);
    const ctx = new ContextBuilder(prisma);
    const step: TemplateStep = {
      scannerName: 'httpx',
      inputs: {},
      target: { kind: 'context', path: 'subdomains' },
    };

    const targets = await ctx.buildTargets(step, makeRun({ target: 'whatever.com' }), 0);

    expect(targets).toEqual([]);
  });

  it('rejects kind=static for step.target (Phase 2 out-of-scope)', async () => {
    const prisma = makePrisma();
    const ctx = new ContextBuilder(prisma);
    const step: TemplateStep = {
      scannerName: 'foo',
      inputs: {},
      target: { kind: 'static', value: 'x' },
    };

    await expect(ctx.buildTargets(step, makeRun(), 0)).rejects.toThrow(/static.*step\.target/i);
  });
});

describe('StepExecutor.runStep — completion polling', () => {
  beforeEach(() => {
    jest.useFakeTimers();
  });
  afterEach(() => {
    jest.useRealTimers();
  });

  it('polling resolves when scanJob.status flips to COMPLETED on 2nd poll', async () => {
    const prisma = makePrisma();
    (prisma.subdomain.findMany as jest.Mock).mockResolvedValueOnce([]);
    const findUnique = prisma.scanJob.findUnique as jest.Mock;
    findUnique.mockResolvedValueOnce({ status: 'RUNNING' });
    findUnique.mockResolvedValueOnce({ status: 'COMPLETED' });

    const registry = makeScannerRegistry(60_000);
    const queue = makeScanQueue();
    const redis = makeRedis();
    const exec = build(prisma, registry, queue, redis, 5_000);

    const run = makeRun();
    const step: TemplateStep = {
      scannerName: 'subfinder',
      inputs: {},
      target: { kind: 'context', path: 'target' },
    };

    const promise = exec.runStep({ templateRun: run, step, stepIndex: 0 });

    // microtask flush: subscribe -> tx (scan.create + scanJob.create) ->
    // queue.add -> schedule first poll. More awaits than pre-refactor
    // because subscribe is now awaited *before* row creation (C1).
    await flushMicrotasks(10);

    // First poll @ t=5s -> still RUNNING
    await jest.advanceTimersByTimeAsync(5_000);
    // Second poll @ t=10s -> COMPLETED
    await jest.advanceTimersByTimeAsync(5_000);

    await expect(promise).resolves.toBeUndefined();
    expect(queue.add).toHaveBeenCalledTimes(1);
    // The scanJobId is generated by StepExecutor (randomUUID); we only
    // care that whatever the BullMQ payload uses matches the id passed to
    // ScanJob.create (so the scan-worker can find the row).
    const enqueuedId = (queue.add.mock.calls[0][1] as { scanJobId: string }).scanJobId;
    const createdId = (
      (prisma.scanJob.create as jest.Mock).mock.calls[0][0] as { data: { id: string } }
    ).data.id;
    expect(enqueuedId).toBe(createdId);
    expect(enqueuedId).toMatch(/^[0-9a-f-]{36}$/);
    expect(queue.add).toHaveBeenCalledWith(
      'scan',
      expect.objectContaining({
        scannerName: 'subfinder',
        target: 'example.com',
        engagementId: 'eng_1',
      }),
    );
    expect(redis.subscribe).toHaveBeenCalled();
    expect(redis.unsubscribe).toHaveBeenCalled();
  });

  it('polling rejects with StepFailedError when status flips to FAILED', async () => {
    const prisma = makePrisma();
    const findUnique = prisma.scanJob.findUnique as jest.Mock;
    findUnique.mockResolvedValueOnce({ status: 'RUNNING' });
    findUnique.mockResolvedValueOnce({
      status: 'FAILED',
      errorMessage: 'docker boom',
    });

    const exec = build(
      makePrisma_(prisma),
      makeScannerRegistry(60_000),
      makeScanQueue(),
      makeRedis(),
      5_000,
    );

    const run = makeRun();
    const step: TemplateStep = {
      scannerName: 'subfinder',
      inputs: {},
      target: { kind: 'context', path: 'target' },
    };

    const promise = exec.runStep({ templateRun: run, step, stepIndex: 0 });
    // Make rejection observable to avoid unhandled promise rejection warnings
    const observed = promise.catch((err: unknown) => err);

    await flushMicrotasks(10);
    await jest.advanceTimersByTimeAsync(5_000);
    await jest.advanceTimersByTimeAsync(5_000);

    const err = await observed;
    expect(err).toBeInstanceOf(StepFailedError);
    expect((err as StepFailedError).message).toMatch(/FAILED/);
  });

  it('polling rejects with StepTimeoutError when status never flips (timeout = defaultTimeoutMs + 60s)', async () => {
    const prisma = makePrisma();
    // Always RUNNING — never flips.
    (prisma.scanJob.findUnique as jest.Mock).mockResolvedValue({
      status: 'RUNNING',
    });

    const registry = makeScannerRegistry(60_000); // step timeout = 60_000 + 60_000 = 120_000
    const exec = build(prisma, registry, makeScanQueue(), makeRedis(), 5_000);

    const run = makeRun();
    const step: TemplateStep = {
      scannerName: 'subfinder',
      inputs: {},
      target: { kind: 'context', path: 'target' },
    };

    const promise = exec.runStep({ templateRun: run, step, stepIndex: 0 });
    const observed = promise.catch((err: unknown) => err);

    // flush microtasks then run past the 120s budget
    await flushMicrotasks(10);
    await jest.advanceTimersByTimeAsync(120_000 + 1);

    const err = await observed;
    expect(err).toBeInstanceOf(StepTimeoutError);
  });
});

describe('StepExecutor.runStep — multi-target enqueue', () => {
  beforeEach(() => {
    jest.useFakeTimers();
  });
  afterEach(() => {
    jest.useRealTimers();
  });

  it('enqueues N ScanJobs (one per target) and waits for all to complete', async () => {
    const prisma = makePrisma();
    (prisma.subdomain.findMany as jest.Mock).mockResolvedValueOnce([
      { canonicalValue: 'a.acme.com' },
      { canonicalValue: 'b.acme.com' },
    ]);

    // Both jobs report COMPLETED on first poll (id-agnostic — we now
    // generate ids via randomUUID, not via the mock).
    (prisma.scanJob.findUnique as jest.Mock).mockImplementation(
      ({ where }: { where: { id: string } }) =>
        Promise.resolve({ id: where.id, status: 'COMPLETED' }),
    );

    const queue = makeScanQueue();
    const exec = build(prisma, makeScannerRegistry(60_000), queue, makeRedis(), 5_000);

    const step: TemplateStep = {
      scannerName: 'httpx',
      inputs: { techDetect: { kind: 'static', value: true } },
      target: { kind: 'context', path: 'subdomains' },
    };

    const promise = exec.runStep({ templateRun: makeRun(), step, stepIndex: 1 });

    await flushMicrotasks(15);
    await jest.advanceTimersByTimeAsync(5_000);

    await expect(promise).resolves.toBeUndefined();
    expect(queue.add).toHaveBeenCalledTimes(2);
    expect(queue.add).toHaveBeenNthCalledWith(
      1,
      'scan',
      expect.objectContaining({ target: 'a.acme.com', input: { techDetect: true } }),
    );
    expect(queue.add).toHaveBeenNthCalledWith(
      2,
      'scan',
      expect.objectContaining({ target: 'b.acme.com', input: { techDetect: true } }),
    );
  });

  it('extracts only static inputs from step.inputs (context inputs are skipped in Phase 2)', async () => {
    const prisma = makePrisma();
    (prisma.scanJob.findUnique as jest.Mock).mockResolvedValue({
      status: 'COMPLETED',
    });

    const queue = makeScanQueue();
    const exec = build(prisma, makeScannerRegistry(60_000), queue, makeRedis(), 5_000);

    const step: TemplateStep = {
      scannerName: 'subfinder',
      inputs: {
        sources: { kind: 'static', value: [] },
        recursive: { kind: 'static', value: false },
        // a context input — must be skipped (Phase 2 out-of-scope)
        seedFrom: { kind: 'context', path: 'subdomains' },
      },
      target: { kind: 'context', path: 'target' },
    };

    const promise = exec.runStep({ templateRun: makeRun(), step, stepIndex: 0 });
    await flushMicrotasks(10);
    await jest.advanceTimersByTimeAsync(5_000);
    await promise;

    const call = queue.add.mock.calls[0];
    expect(call[1].input).toEqual({ sources: [], recursive: false });
    expect((call[1].input as Record<string, unknown>).seedFrom).toBeUndefined();
  });
});

describe('StepExecutor — code-review follow-ups (Task 10)', () => {
  beforeEach(() => {
    jest.useFakeTimers();
  });
  afterEach(() => {
    jest.useRealTimers();
  });

  // C1: subscribe must happen BEFORE scanJob.create so any future publisher
  // emitting between create and subscribe is not lost (the channel name
  // depends on the ScanJob id, which is why we pre-generate it).
  it('C1: redis.subscribe is called before scanJob.create (no subscribe-after-create race)', async () => {
    const prisma = makePrisma();
    (prisma.scanJob.findUnique as jest.Mock).mockResolvedValue({ status: 'COMPLETED' });

    const order: string[] = [];
    (prisma.scan.create as jest.Mock).mockImplementation(
      ({ data }: { data: Record<string, unknown> }) => {
        order.push('scan.create');
        return Promise.resolve({ id: 'scan_1', ...data });
      },
    );
    (prisma.scanJob.create as jest.Mock).mockImplementation(
      ({ data }: { data: Record<string, unknown> }) => {
        order.push('scanJob.create');
        return Promise.resolve({ status: 'PENDING', ...data });
      },
    );

    const redis = makeRedis();
    (redis.subscribe as jest.Mock).mockImplementation((_channel: string) => {
      order.push('redis.subscribe');
      return Promise.resolve();
    });

    const queue = makeScanQueue();
    (queue.add as jest.Mock).mockImplementation(() => {
      order.push('queue.add');
      return Promise.resolve({});
    });

    const exec = build(prisma, makeScannerRegistry(60_000), queue, redis, 5_000);
    const step: TemplateStep = {
      scannerName: 'subfinder',
      inputs: {},
      target: { kind: 'context', path: 'target' },
    };

    const promise = exec.runStep({ templateRun: makeRun(), step, stepIndex: 0 });
    await flushMicrotasks(15);
    await jest.advanceTimersByTimeAsync(5_000);
    await promise;

    // Strict ordering: subscribe -> scan.create -> scanJob.create -> queue.add.
    expect(order).toEqual(['redis.subscribe', 'scan.create', 'scanJob.create', 'queue.add']);
  });

  // C2: scan.create and scanJob.create must run inside the same $transaction
  // so a ScanJob insert failure (constraint, connection) doesn't leak an
  // orphan Scan row.
  it('C2: scan.create and scanJob.create happen inside a single $transaction call', async () => {
    const prisma = makePrisma();
    (prisma.scanJob.findUnique as jest.Mock).mockResolvedValue({ status: 'COMPLETED' });

    // Capture the callback handed to $transaction so we can assert both
    // creates run inside it (and only inside it).
    const $transaction = prisma.$transaction as jest.Mock;
    let creationsInsideTx = 0;
    $transaction.mockImplementationOnce(async (cb: (tx: unknown) => Promise<unknown>) => {
      const txProxy = {
        scan: {
          create: jest.fn().mockImplementation(({ data }: { data: Record<string, unknown> }) => {
            creationsInsideTx += 1;
            return Promise.resolve({ id: 'scan_inside_tx', ...data });
          }),
        },
        scanJob: {
          create: jest.fn().mockImplementation(({ data }: { data: Record<string, unknown> }) => {
            creationsInsideTx += 1;
            return Promise.resolve({ status: 'PENDING', ...data });
          }),
        },
      };
      const result = await cb(txProxy);
      // Both creations must have happened by the time the cb resolves.
      expect(creationsInsideTx).toBe(2);
      return result;
    });

    const exec = build(prisma, makeScannerRegistry(60_000), makeScanQueue(), makeRedis(), 5_000);
    const step: TemplateStep = {
      scannerName: 'subfinder',
      inputs: {},
      target: { kind: 'context', path: 'target' },
    };

    const promise = exec.runStep({ templateRun: makeRun(), step, stepIndex: 0 });
    await flushMicrotasks(15);
    await jest.advanceTimersByTimeAsync(5_000);
    await promise;

    expect($transaction).toHaveBeenCalledTimes(1);
    expect($transaction).toHaveBeenCalledWith(expect.any(Function));
    // The outer prisma.scan.create / prisma.scanJob.create must NOT have
    // been called — only the tx-scoped variants.
    expect(prisma.scan.create).not.toHaveBeenCalled();
    expect(prisma.scanJob.create).not.toHaveBeenCalled();
  });

  // I1: when one parallel target rejects, the surviving target's pollTimer +
  // budgetTimer must tear down via the shared AbortSignal instead of running
  // out the full step budget.
  it("I1: sibling rejection triggers AbortSignal that clears the surviving target's timers", async () => {
    const prisma = makePrisma();
    (prisma.subdomain.findMany as jest.Mock).mockResolvedValueOnce([
      { canonicalValue: 'a.acme.com' },
      { canonicalValue: 'b.acme.com' },
    ]);

    // Target A returns FAILED on first poll; Target B stays RUNNING forever
    // (it should be aborted, not run to the 120s budget).
    const failedIds = new Set<string>();
    let firstCreate = true;
    (prisma.scanJob.create as jest.Mock).mockImplementation(
      ({ data }: { data: Record<string, unknown> }) => {
        if (firstCreate) {
          failedIds.add(data.id as string);
          firstCreate = false;
        }
        return Promise.resolve({ status: 'PENDING', ...data });
      },
    );
    (prisma.scanJob.findUnique as jest.Mock).mockImplementation(
      ({ where }: { where: { id: string } }) =>
        failedIds.has(where.id)
          ? Promise.resolve({ id: where.id, status: 'FAILED', errorMessage: 'boom' })
          : Promise.resolve({ id: where.id, status: 'RUNNING' }),
    );

    const clearIntervalSpy = jest.spyOn(global, 'clearInterval');
    const clearTimeoutSpy = jest.spyOn(global, 'clearTimeout');

    const exec = build(prisma, makeScannerRegistry(60_000), makeScanQueue(), makeRedis(), 5_000);
    const step: TemplateStep = {
      scannerName: 'httpx',
      inputs: {},
      target: { kind: 'context', path: 'subdomains' },
    };

    const promise = exec.runStep({ templateRun: makeRun(), step, stepIndex: 1 });
    const observed = promise.catch((err: unknown) => err);

    await flushMicrotasks(20);
    // First poll @ t=5s — Target A flips to FAILED, AbortController fires,
    // Target B's timers must be torn down.
    await jest.advanceTimersByTimeAsync(5_000);
    await flushMicrotasks(10);

    const err = await observed;
    expect(err).toBeInstanceOf(StepFailedError);

    // Both targets installed a pollTimer + a budgetTimer. After the sibling
    // failure, BOTH targets' timers must be cleared (the rejecting target
    // clears via finishErr; the surviving target clears via the abort
    // listener). So clearInterval should be called >= 2 times, ditto
    // clearTimeout.
    expect(clearIntervalSpy.mock.calls.length).toBeGreaterThanOrEqual(2);
    expect(clearTimeoutSpy.mock.calls.length).toBeGreaterThanOrEqual(2);

    clearIntervalSpy.mockRestore();
    clearTimeoutSpy.mockRestore();
  });

  // I2: SIGTERM must close the Redis subscriber connection cleanly. The
  // OnModuleDestroy hook must call redis.quit().
  it('I2: onModuleDestroy() calls redis.quit() on the subscriber', async () => {
    const prisma = makePrisma();
    const redis = makeRedis();
    const exec = build(prisma, makeScannerRegistry(60_000), makeScanQueue(), redis, 5_000);

    await exec.onModuleDestroy();

    expect(redis.quit).toHaveBeenCalledTimes(1);
  });
});

describe('StepExecutor.runStep — enqueue failure reconciliation', () => {
  // No fake timers: the enqueue throw happens before any polling timer is
  // installed, so we can let the natural promise chain unwind.

  it('marks Scan + ScanJob FAILED and re-throws when scanQueue.add throws', async () => {
    const prisma = makePrisma();
    // makePrisma omits update mocks since the happy path doesn't need them.
    // Reach in and attach jest.fn()s for both surfaces so the reconciliation
    // path has somewhere to land.
    (prisma.scan as unknown as { update: jest.Mock }).update = jest
      .fn()
      .mockResolvedValue({ id: 'scan_1', status: 'FAILED' });
    (prisma.scanJob as unknown as { update: jest.Mock }).update = jest
      .fn()
      .mockResolvedValue({ status: 'FAILED' });

    const queue = makeScanQueue();
    const enqueueError = new Error('redis is down');
    (queue.add as jest.Mock).mockRejectedValueOnce(enqueueError);

    const redis = makeRedis();
    const exec = build(prisma, makeScannerRegistry(60_000), queue, redis, 5_000);

    const step: TemplateStep = {
      scannerName: 'subfinder',
      inputs: {},
      target: { kind: 'context', path: 'target' },
    };

    await expect(exec.runStep({ templateRun: makeRun(), step, stepIndex: 0 })).rejects.toBe(
      enqueueError,
    );

    // Both row updates must have landed before the throw was re-raised.
    const scanUpdate = (prisma.scan as unknown as { update: jest.Mock }).update;
    const scanJobUpdate = (prisma.scanJob as unknown as { update: jest.Mock }).update;
    expect(scanUpdate).toHaveBeenCalledWith({
      where: { id: 'scan_1' },
      data: { status: 'FAILED' },
    });
    const scanJobId = (prisma.scanJob.create as jest.Mock).mock.calls[0][0].data.id as string;
    expect(scanJobUpdate).toHaveBeenCalledWith({
      where: { id: scanJobId },
      data: { status: 'FAILED', errorMessage: 'enqueue failed: redis is down' },
    });
    // Subscriber must be torn down so we don't leak the redis listener.
    expect(redis.unsubscribe).toHaveBeenCalled();
    expect(redis.off).toHaveBeenCalled();
  });

  it('still re-throws the original enqueue error when the FAILED-status updates themselves fail', async () => {
    const prisma = makePrisma();
    (prisma.scan as unknown as { update: jest.Mock }).update = jest
      .fn()
      .mockRejectedValue(new Error('scan db blip'));
    (prisma.scanJob as unknown as { update: jest.Mock }).update = jest
      .fn()
      .mockRejectedValue(new Error('scanJob db blip'));

    const queue = makeScanQueue();
    (queue.add as jest.Mock).mockRejectedValueOnce(new Error('redis is down'));

    const exec = build(prisma, makeScannerRegistry(60_000), queue, makeRedis(), 5_000);

    // Spy on the executor's logger so we can verify both masked-update
    // warns fire — without that signal, an operator hit by Redis-down +
    // DB-flake at once would only see the BullMQ error.
    const warnSpy = jest
      .spyOn((exec as unknown as { logger: { warn: (msg: string) => void } }).logger, 'warn')
      .mockImplementation(() => undefined);

    const step: TemplateStep = {
      scannerName: 'subfinder',
      inputs: {},
      target: { kind: 'context', path: 'target' },
    };

    await expect(exec.runStep({ templateRun: makeRun(), step, stepIndex: 0 })).rejects.toThrow(
      /redis is down/,
    );

    expect(warnSpy).toHaveBeenCalledWith(
      expect.stringMatching(/scan=.*FAILED-status reconciliation failed.*scan db blip/),
    );
    expect(warnSpy).toHaveBeenCalledWith(
      expect.stringMatching(/scanJob=.*FAILED-status reconciliation failed.*scanJob db blip/),
    );
  });
});

// helper local to this file: clones a prisma mock returned by makePrisma so
// we can install additional mock impls without affecting earlier specs.
function makePrisma_(p: jest.Mocked<PrismaService>): jest.Mocked<PrismaService> {
  return p;
}

/**
 * Flushes N microtask ticks. The dispatchOne pipeline (subscribe -> $transaction
 * -> scan.create -> scanJob.create -> queue.add -> awaitScanJobCompletion's
 * Promise constructor) has a non-trivial number of awaits, so tests need to
 * yield enough times for the pollTimer + budgetTimer to be installed before
 * advancing the fake clock.
 */
async function flushMicrotasks(n = 10): Promise<void> {
  for (let i = 0; i < n; i++) {
    await Promise.resolve();
  }
}
