import type { PrismaService } from '@autoscanner/database';
import type { ScannerRegistry } from '@autoscanner/scanner-sdk';
import type { TemplateStep } from '@autoscanner/templates';

import { ContextBuilder } from '../context-builder.service';
import type { OrchestratorRedisSubscriber } from '../orchestrator-redis.tokens';
import { StepExecutor, StepTimeoutError, StepFailedError } from '../step-executor.service';

type TemplateRun = {
  id: string;
  templateId: string;
  templateName: string;
  engagementId: string;
  target: string;
  status: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'CANCELLED';
  currentStepIndex: number;
  startedAt: Date | null;
  completedAt: Date | null;
  errorMessage: string | null;
  createdById: string;
  createdAt: Date;
  updatedAt: Date;
};

function makeRun(overrides: Partial<TemplateRun> = {}): TemplateRun {
  return {
    id: 'run_1',
    templateId: 'tpl_1',
    templateName: 'recon-passif',
    engagementId: 'eng_1',
    target: 'example.com',
    status: 'RUNNING',
    currentStepIndex: 0,
    startedAt: new Date(),
    completedAt: null,
    errorMessage: null,
    createdById: 'user_1',
    createdAt: new Date(),
    updatedAt: new Date(),
    ...overrides,
  };
}

function makePrisma(): jest.Mocked<PrismaService> {
  const prisma = {
    scan: {
      create: jest
        .fn()
        .mockImplementation(({ data }: { data: Record<string, unknown> }) =>
          Promise.resolve({ id: 'scan_1', ...data }),
        ),
    },
    scanJob: {
      // `id` defaults to a random UUID generated by StepExecutor; tests that
      // care about the id assert against the `data.id` echoed back here, or
      // against the `scanJobId` payload published to Kafka.
      create: jest
        .fn()
        .mockImplementation(({ data }: { data: Record<string, unknown> }) =>
          Promise.resolve({ status: 'PENDING', ...data }),
        ),
      findUnique: jest.fn().mockResolvedValue(null),
    },
    // C2: dispatchOne wraps scan+scanJob creation in a single $transaction.
    $transaction: jest.fn(async (cb: (tx: unknown) => Promise<unknown>) => cb(prisma)),
  } as unknown as jest.Mocked<PrismaService>;
  return prisma;
}

function makeRedis(): jest.Mocked<OrchestratorRedisSubscriber> {
  return {
    subscribe: jest.fn().mockResolvedValue(undefined),
    unsubscribe: jest.fn().mockResolvedValue(undefined),
    on: jest.fn(),
    quit: jest.fn().mockResolvedValue(undefined),
  } as unknown as jest.Mocked<OrchestratorRedisSubscriber>;
}

function makeScannerRegistry(timeoutMs = 600_000): ScannerRegistry {
  return {
    get: jest.fn().mockReturnValue({
      name: 'subfinder',
      docker: { defaultTimeoutMs: timeoutMs },
    }),
  } as unknown as ScannerRegistry;
}

function makeScanBus(): { publish: jest.Mock } {
  return {
    publish: jest.fn().mockResolvedValue(undefined),
  };
}

/**
 * A stub ContextBuilder that returns a fixed target list, used to exercise the
 * StepExecutor's fan-out machinery (Promise.all, shared listener, sibling
 * abort). In production SP3a the real ContextBuilder always returns a single
 * `[run.target]`, but the machinery must still be race-safe if it ever fans out.
 */
function makeContextBuilder(targets: string[]): ContextBuilder {
  return { buildTargets: jest.fn().mockResolvedValue(targets) } as unknown as ContextBuilder;
}

function build(
  prisma: jest.Mocked<PrismaService>,
  registry: ScannerRegistry,
  bus: { publish: jest.Mock },
  redis: jest.Mocked<OrchestratorRedisSubscriber>,
  pollIntervalMs = 5_000,
  ctxBuilder: ContextBuilder = new ContextBuilder(),
): StepExecutor {
  return new StepExecutor(prisma, registry, bus, redis, ctxBuilder, { pollIntervalMs });
}

describe('ContextBuilder integration — target resolution (SP3a)', () => {
  it('resolves every step to the run root target', async () => {
    const ctx = new ContextBuilder();
    const run = makeRun({ target: 'acme.com' });
    const step: TemplateStep = { scannerName: 'nmap', args: '-sV -Pn' };

    await expect(ctx.buildTargets(step, run, 0)).resolves.toEqual(['acme.com']);
    await expect(ctx.buildTargets(step, run, 4)).resolves.toEqual(['acme.com']);
  });
});

describe('StepExecutor.runStep — completion polling', () => {
  beforeEach(() => {
    jest.useFakeTimers();
  });
  afterEach(() => {
    jest.useRealTimers();
  });

  it('publishes child input { args } and target = run root, resolving on COMPLETED', async () => {
    const prisma = makePrisma();
    const findUnique = prisma.scanJob.findUnique as jest.Mock;
    findUnique.mockResolvedValueOnce({ status: 'RUNNING' });
    findUnique.mockResolvedValueOnce({ status: 'COMPLETED' });

    const registry = makeScannerRegistry(60_000);
    const bus = makeScanBus();
    const redis = makeRedis();
    const exec = build(prisma, registry, bus, redis, 5_000);

    const run = makeRun({ target: 'acme.com' });
    const step: TemplateStep = { scannerName: 'nmap', args: '-sV -Pn' };

    const promise = exec.runStep({ templateRun: run, step, stepIndex: 0 });

    await flushMicrotasks(10);
    await jest.advanceTimersByTimeAsync(5_000); // still RUNNING
    await jest.advanceTimersByTimeAsync(5_000); // COMPLETED

    await expect(promise).resolves.toBeUndefined();
    expect(bus.publish).toHaveBeenCalledTimes(1);

    // Child input carries ONLY the generic Kali scanner keys ({ args }); no
    // legacy structured option keys.
    const payload = bus.publish.mock.calls[0][2] as {
      scanJobId: string;
      scannerName: string;
      target: string;
      input: Record<string, unknown>;
    };
    expect(payload.scannerName).toBe('nmap');
    expect(payload.target).toBe('acme.com');
    expect(payload.input).toEqual({ args: '-sV -Pn' });

    // The scanJobId is generated by StepExecutor (randomUUID); it must match the
    // id used to create the ScanJob row so the scan-worker can find it.
    const createdId = (
      (prisma.scanJob.create as jest.Mock).mock.calls[0][0] as { data: { id: string } }
    ).data.id;
    expect(payload.scanJobId).toBe(createdId);
    expect(payload.scanJobId).toMatch(/^[0-9a-f-]{36}$/);

    // ScanJob row records the same target + input.
    const jobData = (prisma.scanJob.create as jest.Mock).mock.calls[0][0].data as {
      target: string;
      input: Record<string, unknown>;
    };
    expect(jobData.target).toBe('acme.com');
    expect(jobData.input).toEqual({ args: '-sV -Pn' });

    expect(redis.subscribe).toHaveBeenCalled();
    expect(redis.unsubscribe).toHaveBeenCalled();
  });

  it('omits args/preset when the step has neither (empty input object)', async () => {
    const prisma = makePrisma();
    (prisma.scanJob.findUnique as jest.Mock).mockResolvedValue({ status: 'COMPLETED' });

    const bus = makeScanBus();
    const exec = build(prisma, makeScannerRegistry(60_000), bus, makeRedis(), 5_000);

    const step: TemplateStep = { scannerName: 'whatweb' };
    const promise = exec.runStep({ templateRun: makeRun(), step, stepIndex: 0 });
    await flushMicrotasks(10);
    await jest.advanceTimersByTimeAsync(5_000);
    await promise;

    expect(bus.publish.mock.calls[0][2].input).toEqual({});
  });

  it('includes preset when set', async () => {
    const prisma = makePrisma();
    (prisma.scanJob.findUnique as jest.Mock).mockResolvedValue({ status: 'COMPLETED' });

    const bus = makeScanBus();
    const exec = build(prisma, makeScannerRegistry(60_000), bus, makeRedis(), 5_000);

    const step: TemplateStep = { scannerName: 'amass', args: 'enum -passive', preset: 'fast' };
    const promise = exec.runStep({ templateRun: makeRun(), step, stepIndex: 1 });
    await flushMicrotasks(10);
    await jest.advanceTimersByTimeAsync(5_000);
    await promise;

    expect(bus.publish.mock.calls[0][2].input).toEqual({ args: 'enum -passive', preset: 'fast' });
  });

  it('polling rejects with StepFailedError when status flips to FAILED', async () => {
    const prisma = makePrisma();
    const findUnique = prisma.scanJob.findUnique as jest.Mock;
    findUnique.mockResolvedValueOnce({ status: 'RUNNING' });
    findUnique.mockResolvedValueOnce({ status: 'FAILED', errorMessage: 'docker boom' });

    const exec = build(prisma, makeScannerRegistry(60_000), makeScanBus(), makeRedis(), 5_000);

    const step: TemplateStep = { scannerName: 'nmap', args: '-sV' };
    const promise = exec.runStep({ templateRun: makeRun(), step, stepIndex: 0 });
    const observed = promise.catch((err: unknown) => err);

    await flushMicrotasks(10);
    await jest.advanceTimersByTimeAsync(5_000);
    await jest.advanceTimersByTimeAsync(5_000);

    const err = await observed;
    expect(err).toBeInstanceOf(StepFailedError);
    expect((err as StepFailedError).message).toMatch(/FAILED/);
  });

  it('polling rejects with StepTimeoutError when status never flips (timeout = defaultTimeoutMs + 60s)', async () => {
    const prisma = makePrisma();
    (prisma.scanJob.findUnique as jest.Mock).mockResolvedValue({ status: 'RUNNING' });

    const registry = makeScannerRegistry(60_000); // step timeout = 60_000 + 60_000 = 120_000
    const exec = build(prisma, registry, makeScanBus(), makeRedis(), 5_000);

    const step: TemplateStep = { scannerName: 'nmap', args: '-sV' };
    const promise = exec.runStep({ templateRun: makeRun(), step, stepIndex: 0 });
    const observed = promise.catch((err: unknown) => err);

    await flushMicrotasks(10);
    await jest.advanceTimersByTimeAsync(120_000 + 1);

    const err = await observed;
    expect(err).toBeInstanceOf(StepTimeoutError);
  });
});

describe('StepExecutor.runStep — fan-out machinery (stubbed multi-target)', () => {
  beforeEach(() => {
    jest.useFakeTimers();
  });
  afterEach(() => {
    jest.useRealTimers();
  });

  it('enqueues N ScanJobs (one per target) and waits for all to complete', async () => {
    const prisma = makePrisma();
    (prisma.scanJob.findUnique as jest.Mock).mockImplementation(
      ({ where }: { where: { id: string } }) =>
        Promise.resolve({ id: where.id, status: 'COMPLETED' }),
    );

    const bus = makeScanBus();
    const ctx = makeContextBuilder(['a.acme.com', 'b.acme.com']);
    const exec = build(prisma, makeScannerRegistry(60_000), bus, makeRedis(), 5_000, ctx);

    const step: TemplateStep = { scannerName: 'httpx', args: '-td' };
    const promise = exec.runStep({ templateRun: makeRun(), step, stepIndex: 1 });

    await flushMicrotasks(15);
    await jest.advanceTimersByTimeAsync(5_000);

    await expect(promise).resolves.toBeUndefined();
    expect(bus.publish).toHaveBeenCalledTimes(2);
    expect(bus.publish).toHaveBeenNthCalledWith(
      1,
      'security.scanner.requested',
      expect.any(String),
      expect.objectContaining({ target: 'a.acme.com', input: { args: '-td' } }),
    );
    expect(bus.publish).toHaveBeenNthCalledWith(
      2,
      'security.scanner.requested',
      expect.any(String),
      expect.objectContaining({ target: 'b.acme.com', input: { args: '-td' } }),
    );
  });

  it('binds the redis `message` listener at most once regardless of fan-out', async () => {
    const prisma = makePrisma();
    (prisma.scanJob.findUnique as jest.Mock).mockImplementation(
      ({ where }: { where: { id: string } }) =>
        Promise.resolve({ id: where.id, status: 'COMPLETED' }),
    );

    const redis = makeRedis();
    const ctx = makeContextBuilder(['a.acme.com', 'b.acme.com', 'c.acme.com']);
    const exec = build(prisma, makeScannerRegistry(60_000), makeScanBus(), redis, 5_000, ctx);

    const step: TemplateStep = { scannerName: 'httpx' };
    const promise = exec.runStep({ templateRun: makeRun(), step, stepIndex: 0 });
    await flushMicrotasks(15);
    await jest.advanceTimersByTimeAsync(5_000);
    await promise;

    const messageListenerCalls = (redis.on as jest.Mock).mock.calls.filter(
      ([event]) => event === 'message',
    );
    expect(messageListenerCalls).toHaveLength(1);
    expect(redis.subscribe).toHaveBeenCalledTimes(3);
  });

  // I1: when one parallel target rejects, the surviving target's pollTimer +
  // budgetTimer must tear down via the shared AbortSignal instead of running
  // out the full step budget.
  it("I1: sibling rejection triggers AbortSignal that clears the surviving target's timers", async () => {
    const prisma = makePrisma();

    const failedIds = new Set<string>();
    let firstCreate = true;
    (prisma.scanJob.create as jest.Mock).mockImplementation(
      ({ data }: { data: Record<string, unknown> }) => {
        if (firstCreate) {
          failedIds.add(data.id as string);
          firstCreate = false;
        }
        return Promise.resolve({ status: 'PENDING', ...data });
      },
    );
    (prisma.scanJob.findUnique as jest.Mock).mockImplementation(
      ({ where }: { where: { id: string } }) =>
        failedIds.has(where.id)
          ? Promise.resolve({ id: where.id, status: 'FAILED', errorMessage: 'boom' })
          : Promise.resolve({ id: where.id, status: 'RUNNING' }),
    );

    const clearIntervalSpy = jest.spyOn(global, 'clearInterval');
    const clearTimeoutSpy = jest.spyOn(global, 'clearTimeout');

    const ctx = makeContextBuilder(['a.acme.com', 'b.acme.com']);
    const exec = build(prisma, makeScannerRegistry(60_000), makeScanBus(), makeRedis(), 5_000, ctx);

    const step: TemplateStep = { scannerName: 'httpx' };
    const promise = exec.runStep({ templateRun: makeRun(), step, stepIndex: 1 });
    const observed = promise.catch((err: unknown) => err);

    await flushMicrotasks(20);
    await jest.advanceTimersByTimeAsync(5_000);
    await flushMicrotasks(10);

    const err = await observed;
    expect(err).toBeInstanceOf(StepFailedError);

    expect(clearIntervalSpy.mock.calls.length).toBeGreaterThanOrEqual(2);
    expect(clearTimeoutSpy.mock.calls.length).toBeGreaterThanOrEqual(2);

    clearIntervalSpy.mockRestore();
    clearTimeoutSpy.mockRestore();
  });
});

describe('StepExecutor — code-review follow-ups (Task 10)', () => {
  beforeEach(() => {
    jest.useFakeTimers();
  });
  afterEach(() => {
    jest.useRealTimers();
  });

  // C1: subscribe must happen BEFORE scanJob.create so any future publisher
  // emitting between create and subscribe is not lost.
  it('C1: redis.subscribe is called before scanJob.create (no subscribe-after-create race)', async () => {
    const prisma = makePrisma();
    (prisma.scanJob.findUnique as jest.Mock).mockResolvedValue({ status: 'COMPLETED' });

    const order: string[] = [];
    (prisma.scan.create as jest.Mock).mockImplementation(
      ({ data }: { data: Record<string, unknown> }) => {
        order.push('scan.create');
        return Promise.resolve({ id: 'scan_1', ...data });
      },
    );
    (prisma.scanJob.create as jest.Mock).mockImplementation(
      ({ data }: { data: Record<string, unknown> }) => {
        order.push('scanJob.create');
        return Promise.resolve({ status: 'PENDING', ...data });
      },
    );

    const redis = makeRedis();
    (redis.subscribe as jest.Mock).mockImplementation((_channel: string) => {
      order.push('redis.subscribe');
      return Promise.resolve();
    });

    const bus = makeScanBus();
    (bus.publish as jest.Mock).mockImplementation(() => {
      order.push('bus.publish');
      return Promise.resolve({});
    });

    const exec = build(prisma, makeScannerRegistry(60_000), bus, redis, 5_000);
    const step: TemplateStep = { scannerName: 'nmap', args: '-sV' };

    const promise = exec.runStep({ templateRun: makeRun(), step, stepIndex: 0 });
    await flushMicrotasks(15);
    await jest.advanceTimersByTimeAsync(5_000);
    await promise;

    expect(order).toEqual(['redis.subscribe', 'scan.create', 'scanJob.create', 'bus.publish']);
  });

  // C2: scan.create and scanJob.create must run inside the same $transaction.
  it('C2: scan.create and scanJob.create happen inside a single $transaction call', async () => {
    const prisma = makePrisma();
    (prisma.scanJob.findUnique as jest.Mock).mockResolvedValue({ status: 'COMPLETED' });

    const $transaction = prisma.$transaction as jest.Mock;
    let creationsInsideTx = 0;
    $transaction.mockImplementationOnce(async (cb: (tx: unknown) => Promise<unknown>) => {
      const txProxy = {
        scan: {
          create: jest.fn().mockImplementation(({ data }: { data: Record<string, unknown> }) => {
            creationsInsideTx += 1;
            return Promise.resolve({ id: 'scan_inside_tx', ...data });
          }),
        },
        scanJob: {
          create: jest.fn().mockImplementation(({ data }: { data: Record<string, unknown> }) => {
            creationsInsideTx += 1;
            return Promise.resolve({ status: 'PENDING', ...data });
          }),
        },
      };
      const result = await cb(txProxy);
      expect(creationsInsideTx).toBe(2);
      return result;
    });

    const exec = build(prisma, makeScannerRegistry(60_000), makeScanBus(), makeRedis(), 5_000);
    const step: TemplateStep = { scannerName: 'nmap', args: '-sV' };

    const promise = exec.runStep({ templateRun: makeRun(), step, stepIndex: 0 });
    await flushMicrotasks(15);
    await jest.advanceTimersByTimeAsync(5_000);
    await promise;

    expect($transaction).toHaveBeenCalledTimes(1);
    expect($transaction).toHaveBeenCalledWith(expect.any(Function));
    expect(prisma.scan.create).not.toHaveBeenCalled();
    expect(prisma.scanJob.create).not.toHaveBeenCalled();
  });

  // I2: SIGTERM must close the Redis subscriber connection cleanly.
  it('I2: onModuleDestroy() calls redis.quit() on the subscriber', async () => {
    const prisma = makePrisma();
    const redis = makeRedis();
    const exec = build(prisma, makeScannerRegistry(60_000), makeScanBus(), redis, 5_000);

    await exec.onModuleDestroy();

    expect(redis.quit).toHaveBeenCalledTimes(1);
  });
});

describe('StepExecutor.runStep — enqueue failure reconciliation', () => {
  it('marks Scan + ScanJob FAILED and re-throws when the publish throws', async () => {
    const prisma = makePrisma();
    (prisma.scan as unknown as { update: jest.Mock }).update = jest
      .fn()
      .mockResolvedValue({ id: 'scan_1', status: 'FAILED' });
    (prisma.scanJob as unknown as { update: jest.Mock }).update = jest
      .fn()
      .mockResolvedValue({ status: 'FAILED' });

    const bus = makeScanBus();
    const enqueueError = new Error('redis is down');
    (bus.publish as jest.Mock).mockRejectedValueOnce(enqueueError);

    const redis = makeRedis();
    const exec = build(prisma, makeScannerRegistry(60_000), bus, redis, 5_000);

    const step: TemplateStep = { scannerName: 'nmap', args: '-sV' };

    await expect(exec.runStep({ templateRun: makeRun(), step, stepIndex: 0 })).rejects.toBe(
      enqueueError,
    );

    const scanUpdate = (prisma.scan as unknown as { update: jest.Mock }).update;
    const scanJobUpdate = (prisma.scanJob as unknown as { update: jest.Mock }).update;
    expect(scanUpdate).toHaveBeenCalledWith({
      where: { id: 'scan_1' },
      data: { status: 'FAILED' },
    });
    const scanJobId = (prisma.scanJob.create as jest.Mock).mock.calls[0][0].data.id as string;
    expect(scanJobUpdate).toHaveBeenCalledWith({
      where: { id: scanJobId },
      data: { status: 'FAILED', errorMessage: 'enqueue failed: redis is down' },
    });
    expect(redis.unsubscribe).toHaveBeenCalled();
  });

  it('still re-throws the original enqueue error when the FAILED-status updates themselves fail', async () => {
    const prisma = makePrisma();
    (prisma.scan as unknown as { update: jest.Mock }).update = jest
      .fn()
      .mockRejectedValue(new Error('scan db blip'));
    (prisma.scanJob as unknown as { update: jest.Mock }).update = jest
      .fn()
      .mockRejectedValue(new Error('scanJob db blip'));

    const bus = makeScanBus();
    (bus.publish as jest.Mock).mockRejectedValueOnce(new Error('redis is down'));

    const exec = build(prisma, makeScannerRegistry(60_000), bus, makeRedis(), 5_000);

    const warnSpy = jest
      .spyOn((exec as unknown as { logger: { warn: (msg: string) => void } }).logger, 'warn')
      .mockImplementation(() => undefined);

    const step: TemplateStep = { scannerName: 'nmap', args: '-sV' };

    await expect(exec.runStep({ templateRun: makeRun(), step, stepIndex: 0 })).rejects.toThrow(
      /redis is down/,
    );

    expect(warnSpy).toHaveBeenCalledWith(
      expect.stringMatching(/scan=.*FAILED-status reconciliation failed.*scan db blip/),
    );
    expect(warnSpy).toHaveBeenCalledWith(
      expect.stringMatching(/scanJob=.*FAILED-status reconciliation failed.*scanJob db blip/),
    );
  });
});

/**
 * Flushes N microtask ticks. The dispatchOne pipeline (subscribe -> $transaction
 * -> scan.create -> scanJob.create -> bus.publish -> awaitScanJobCompletion's
 * Promise constructor) has a non-trivial number of awaits, so tests need to
 * yield enough times for the pollTimer + budgetTimer to be installed before
 * advancing the fake clock.
 */
async function flushMicrotasks(n = 10): Promise<void> {
  for (let i = 0; i < n; i++) {
    await Promise.resolve();
  }
}
