export { canonicalDomain, canonicalIp, canonicalize, canonicalizeUrl } from './canonical';
export type { CanonicalizeOptions } from './canonical';
export { findingDedupHash } from './finding-dedup';
export type { FindingDedupHashInput } from './finding-dedup';
export { AssetMergeService } from './asset-merge.service';
export { CorrelationModule } from './correlation.module';
export { computeRiskScore, SENSITIVE_PORTS, ADMIN_TOKENS } from './risk-score';
export type { RiskScoreInput } from './risk-score';
export { recomputeRiskScoreForAsset } from './recompute-risk-score';
export type { PrismaLike } from './recompute-risk-score';
export { writeObservation } from './observation-writer';
export type { WriteObservationInput, ObservationWriterClient } from './observation-writer';
