-- AlterEnum
ALTER TYPE "OrgMetadataKind" ADD VALUE IF NOT EXISTS 'CLOUD_BUCKET';

-- AlterEnum
ALTER TYPE "ApiProvider" ADD VALUE IF NOT EXISTS 'GITHUB';

-- AlterEnum
ALTER TYPE "ApiProvider" ADD VALUE IF NOT EXISTS 'SECURITYTRAILS';
